package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Creates, updates, and deletes tags in an ElasticSearch index.",
    "title": "Tag Registration Service",
    "version": "1.0.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Displays general infrormation about the service and can be used to determine whether or not the service is running.",
        "tags": [
          "status"
        ],
        "summary": "Service Status Information",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/service-info"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "service-info": {
      "type": "object",
      "required": [
        "description",
        "service",
        "version"
      ],
      "properties": {
        "description": {
          "description": "A brief description of the service.",
          "type": "string",
          "minLength": 1
        },
        "service": {
          "description": "The name of the service.",
          "type": "string",
          "minLength": 1
        },
        "version": {
          "description": "The service's version number.",
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
